version: '3'

vars:
  ABI: FreeBSD:14:amd64
  OUT_DIR: build/{{.ABI}}
  PKG_NAME: opnsense-theme-mytheme-1.0.txz

tasks:
  clean:
    cmds:
      - rm -rf build

  build:
    deps: [clean]
    cmds:
      - mkdir -p {{.OUT_DIR}}
      - cp packages/{{.PKG_NAME}} {{.OUT_DIR}}/

  repo:
    deps: [build]
    cmds:
      - pkg repo {{.OUT_DIR}}

  publish:
    deps: [repo]
    cmds:
      - cp -r build docs  # GitHub Pages looks in docs/

  all:
    deps: [publish]
