PLUGIN_NAME=		theme-unsense
PLUGIN_VERSION=		0.2
PLUGIN_REVISION=    1
PLUGIN_COMMENT=		Unsense theme
PLUGIN_MAINTAINER=	peter@froggle.org
LOCALBASE = /usr/local/opnsense/www/themes/unsense

.include "../../Mk/plugins.mk"
