name: Build and Push Unsense Theme

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup yarn
        run: |
          corepack enable
          corepack prepare yarn@1.22.22 --activate

      - name: Build theme
        working-directory: src/unsense-theme
        run: |
          yarn install --mode=update-lockfile
          yarn build
          rm -rf node_modules
          
      - name: Package and index in FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          upload: ./
          mountdir: work/unsense-repo/unsense-repo
          usesh: true
          copyback: true
          prepare: |
            pkg install -y bash gtar pkg
          run: |
            set -ex
            THEME_DIR=${GITHUB_WORKSPACE}/src/unsense-theme
            cd ${THEME_DIR}
            sh scripts/package.sh

            REPO=${THEME_DIR}/repo/FreeBSD_14_amd64
            # mkdir -p "$REPO/unpacked"
            # for p in "$REPO"/*.txz; do
            #   case "$p" in
            #     *repo.txz) continue ;;
            #     *) tar -xvf "$p" -C "$REPO/unpacked" ;;
            #   esac
            # done
            find $REPO/
            pkg repo "$REPO"
            false

      - name: Copy package and index to docs
        run: |
          mkdir -p docs/FreeBSD_14_amd64
          cp -v src/unsense-theme/repo/FreeBSD_14_amd64/* docs/FreeBSD_14_amd64/
          # mv docs/FreeBSD_14_amd64/ docs/FreeBSD:14:amd64/

      - name: Generate index.html from index.md
        run: |
          cp -rv src/www/assets/* docs/
          pandoc --standalone \
            --css=simple.css \
            src/www/index.md \
            -o docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
