name: Build and Push Unsense Theme

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup yarn
        run: |
          corepack enable
          corepack prepare yarn@1.22.22 --activate

      - name: Build theme
        working-directory: src/unsense-theme
        run: |
          yarn install --mode=update-lockfile
          yarn build
          rm -rf node_modules

      - name: Package and index in FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          upload: ./src/unsense-theme
          mountdir: unsense-theme
          usesh: true
          copyback: true
          prepare: |
            pkg install -y bash gtar pkg
          run: |
            set -e
            cd ~/unsense-theme
            sh scripts/package.sh

            REPO=repo/FreeBSD:14:amd64
            mkdir -p "$REPO/unpacked"
            for p in "$REPO"/*.txz; do
              case "$p" in
                *repo.txz) continue ;;
                *) tar -xf "$p" -C "$REPO/unpacked" ;;
              esac
            done
            pkg repo "$REPO"

      - name: Copy package and index to docs
        run: |
          mkdir -p docs/FreeBSD:14:amd64
          cp -v src/unsense-theme/repo/FreeBSD:14:amd64/* docs/FreeBSD:14:amd64/

      - name: Generate index.html from index.md
        run: |
          cp -rv src/www/assets/* docs/
          pandoc --standalone \
            --css=simple.css \
            src/www/index.md \
            -o docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
