name: Build and Push Unsense Theme

on:
  release:
    types: [published]
  workflow_dispatch:
  # push:
    # branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment
        run: sudo apt-get update && sudo apt-get install -y xz-utils pandoc

      - name: Build theme package
        working-directory: src/unsense-theme
        run: |
          yarn install
          yarn build
          sh scripts/package.sh

      - name: Copy built package to docs
        run: |
          mkdir -p docs/FreeBSD:14:amd64
          cp repo/FreeBSD:14:amd64/*.txz docs/FreeBSD:14:amd64/

      - name: Build FreeBSD repo metadata
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y pkg

          run: |
            set -e
            REPO_DIR=/github/workspace/docs/FreeBSD:14:amd64
            mkdir -p "$REPO_DIR/unpacked"

            for p in "$REPO_DIR"/*.txz; do
              tar -xf "$p" -C "$REPO_DIR/unpacked"
            done

            pkg create -m "$REPO_DIR/unpacked/+MANIFEST" \
              -r "$REPO_DIR/unpacked/usr" \
              -p /dev/null \
              -o "$REPO_DIR"

            pkg repo "$REPO_DIR"


      - name: Generate index.html from index.md
        run: |
          cp -rv src/www/assets/* docs/
          pandoc --standalone \
            --css=simple.css \
            src/www/index.md \
            -o docs/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
